/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ReflexProof {
  export type ReflexEventStruct = {
    eventId: BigNumberish;
    organizer: AddressLike;
    eventCID: string;
    startTime: BigNumberish;
    endTime: BigNumberish;
    rulesHash: BytesLike;
  };

  export type ReflexEventStructOutput = [
    eventId: bigint,
    organizer: string,
    eventCID: string,
    startTime: bigint,
    endTime: bigint,
    rulesHash: string
  ] & {
    eventId: bigint;
    organizer: string;
    eventCID: string;
    startTime: bigint;
    endTime: bigint;
    rulesHash: string;
  };

  export type ResultViewStruct = {
    resultId: BigNumberish;
    player: AddressLike;
    mode: BigNumberish;
    resultCID: string;
    resultHash: BytesLike;
    visibility: BigNumberish;
    valueMs: BigNumberish;
    eventId: BigNumberish;
    submittedAt: BigNumberish;
    deviceHash: BytesLike;
    rounds: BigNumberish;
    verified: boolean;
    certificateTokenId: BigNumberish;
  };

  export type ResultViewStructOutput = [
    resultId: bigint,
    player: string,
    mode: bigint,
    resultCID: string,
    resultHash: string,
    visibility: bigint,
    valueMs: bigint,
    eventId: bigint,
    submittedAt: bigint,
    deviceHash: string,
    rounds: bigint,
    verified: boolean,
    certificateTokenId: bigint
  ] & {
    resultId: bigint;
    player: string;
    mode: bigint;
    resultCID: string;
    resultHash: string;
    visibility: bigint;
    valueMs: bigint;
    eventId: bigint;
    submittedAt: bigint;
    deviceHash: string;
    rounds: bigint;
    verified: boolean;
    certificateTokenId: bigint;
  };

  export type SubmitParamsStruct = {
    resultHash: BytesLike;
    resultCID: string;
    valueMs: BigNumberish;
    mode: BigNumberish;
    visibility: BigNumberish;
    eventId: BigNumberish;
    deviceHash: BytesLike;
    rounds: BigNumberish;
    encryptedValue: BytesLike;
    encryptedProof: BytesLike;
  };

  export type SubmitParamsStructOutput = [
    resultHash: string,
    resultCID: string,
    valueMs: bigint,
    mode: bigint,
    visibility: bigint,
    eventId: bigint,
    deviceHash: string,
    rounds: bigint,
    encryptedValue: string,
    encryptedProof: string
  ] & {
    resultHash: string;
    resultCID: string;
    valueMs: bigint;
    mode: bigint;
    visibility: bigint;
    eventId: bigint;
    deviceHash: string;
    rounds: bigint;
    encryptedValue: string;
    encryptedProof: string;
  };
}

export interface ReflexProofInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "ORGANIZER_ROLE"
      | "VERIFIER_ROLE"
      | "awardCertificate"
      | "certificate"
      | "certificateAddress"
      | "confidentialProtocolId"
      | "createEvent"
      | "getEncryptedValue"
      | "getEvent"
      | "getResult"
      | "getRoleAdmin"
      | "grantDecrypt"
      | "grantRole"
      | "hasRole"
      | "renounceRole"
      | "revealResult"
      | "revokeRole"
      | "submitResult"
      | "supportsInterface"
      | "totalEvents"
      | "totalResults"
      | "verifyResult"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateMinted"
      | "DecryptPermissionGranted"
      | "EventCreated"
      | "ResultRevealed"
      | "ResultSubmitted"
      | "ResultVerified"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORGANIZER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "awardCertificate",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "certificate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "certificateAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createEvent",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantDecrypt",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealResult",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [ReflexProof.SubmitParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalEvents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalResults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyResult",
    values: [BigNumberish, boolean, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORGANIZER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "awardCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificateAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyResult",
    data: BytesLike
  ): Result;
}

export namespace CertificateMintedEvent {
  export type InputTuple = [
    resultId: BigNumberish,
    tokenId: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [resultId: bigint, tokenId: bigint, to: string];
  export interface OutputObject {
    resultId: bigint;
    tokenId: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptPermissionGrantedEvent {
  export type InputTuple = [resultId: BigNumberish, to: AddressLike];
  export type OutputTuple = [resultId: bigint, to: string];
  export interface OutputObject {
    resultId: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventCreatedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    organizer: AddressLike,
    eventCID: string
  ];
  export type OutputTuple = [
    eventId: bigint,
    organizer: string,
    eventCID: string
  ];
  export interface OutputObject {
    eventId: bigint;
    organizer: string;
    eventCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultRevealedEvent {
  export type InputTuple = [
    resultId: BigNumberish,
    valueMs: BigNumberish,
    plainCID: string
  ];
  export type OutputTuple = [
    resultId: bigint,
    valueMs: bigint,
    plainCID: string
  ];
  export interface OutputObject {
    resultId: bigint;
    valueMs: bigint;
    plainCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultSubmittedEvent {
  export type InputTuple = [
    resultId: BigNumberish,
    player: AddressLike,
    resultHash: BytesLike,
    visibility: BigNumberish,
    eventId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    resultId: bigint,
    player: string,
    resultHash: string,
    visibility: bigint,
    eventId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    resultId: bigint;
    player: string;
    resultHash: string;
    visibility: bigint;
    eventId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultVerifiedEvent {
  export type InputTuple = [
    resultId: BigNumberish,
    verifier: AddressLike,
    approved: boolean,
    verifyCID: string
  ];
  export type OutputTuple = [
    resultId: bigint,
    verifier: string,
    approved: boolean,
    verifyCID: string
  ];
  export interface OutputObject {
    resultId: bigint;
    verifier: string;
    approved: boolean;
    verifyCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReflexProof extends BaseContract {
  connect(runner?: ContractRunner | null): ReflexProof;
  waitForDeployment(): Promise<this>;

  interface: ReflexProofInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ORGANIZER_ROLE: TypedContractMethod<[], [string], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  awardCertificate: TypedContractMethod<
    [resultId: BigNumberish, to: AddressLike, certCID: string],
    [bigint],
    "nonpayable"
  >;

  certificate: TypedContractMethod<[], [string], "view">;

  certificateAddress: TypedContractMethod<[], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createEvent: TypedContractMethod<
    [
      eventCID: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      rulesHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getEncryptedValue: TypedContractMethod<
    [resultId: BigNumberish],
    [string],
    "view"
  >;

  getEvent: TypedContractMethod<
    [eventId: BigNumberish],
    [ReflexProof.ReflexEventStructOutput],
    "view"
  >;

  getResult: TypedContractMethod<
    [resultId: BigNumberish],
    [ReflexProof.ResultViewStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantDecrypt: TypedContractMethod<
    [resultId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revealResult: TypedContractMethod<
    [resultId: BigNumberish, valueMs: BigNumberish, plainCID: string],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  submitResult: TypedContractMethod<
    [params: ReflexProof.SubmitParamsStruct],
    [bigint],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalEvents: TypedContractMethod<[], [bigint], "view">;

  totalResults: TypedContractMethod<[], [bigint], "view">;

  verifyResult: TypedContractMethod<
    [resultId: BigNumberish, approved: boolean, verifyCID: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ORGANIZER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "awardCertificate"
  ): TypedContractMethod<
    [resultId: BigNumberish, to: AddressLike, certCID: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "certificate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "certificateAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createEvent"
  ): TypedContractMethod<
    [
      eventCID: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      rulesHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedValue"
  ): TypedContractMethod<[resultId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEvent"
  ): TypedContractMethod<
    [eventId: BigNumberish],
    [ReflexProof.ReflexEventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [resultId: BigNumberish],
    [ReflexProof.ResultViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantDecrypt"
  ): TypedContractMethod<
    [resultId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revealResult"
  ): TypedContractMethod<
    [resultId: BigNumberish, valueMs: BigNumberish, plainCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [params: ReflexProof.SubmitParamsStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalEvents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalResults"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyResult"
  ): TypedContractMethod<
    [resultId: BigNumberish, approved: boolean, verifyCID: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CertificateMinted"
  ): TypedContractEvent<
    CertificateMintedEvent.InputTuple,
    CertificateMintedEvent.OutputTuple,
    CertificateMintedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptPermissionGranted"
  ): TypedContractEvent<
    DecryptPermissionGrantedEvent.InputTuple,
    DecryptPermissionGrantedEvent.OutputTuple,
    DecryptPermissionGrantedEvent.OutputObject
  >;
  getEvent(
    key: "EventCreated"
  ): TypedContractEvent<
    EventCreatedEvent.InputTuple,
    EventCreatedEvent.OutputTuple,
    EventCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ResultRevealed"
  ): TypedContractEvent<
    ResultRevealedEvent.InputTuple,
    ResultRevealedEvent.OutputTuple,
    ResultRevealedEvent.OutputObject
  >;
  getEvent(
    key: "ResultSubmitted"
  ): TypedContractEvent<
    ResultSubmittedEvent.InputTuple,
    ResultSubmittedEvent.OutputTuple,
    ResultSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ResultVerified"
  ): TypedContractEvent<
    ResultVerifiedEvent.InputTuple,
    ResultVerifiedEvent.OutputTuple,
    ResultVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "CertificateMinted(uint256,uint256,address)": TypedContractEvent<
      CertificateMintedEvent.InputTuple,
      CertificateMintedEvent.OutputTuple,
      CertificateMintedEvent.OutputObject
    >;
    CertificateMinted: TypedContractEvent<
      CertificateMintedEvent.InputTuple,
      CertificateMintedEvent.OutputTuple,
      CertificateMintedEvent.OutputObject
    >;

    "DecryptPermissionGranted(uint256,address)": TypedContractEvent<
      DecryptPermissionGrantedEvent.InputTuple,
      DecryptPermissionGrantedEvent.OutputTuple,
      DecryptPermissionGrantedEvent.OutputObject
    >;
    DecryptPermissionGranted: TypedContractEvent<
      DecryptPermissionGrantedEvent.InputTuple,
      DecryptPermissionGrantedEvent.OutputTuple,
      DecryptPermissionGrantedEvent.OutputObject
    >;

    "EventCreated(uint256,address,string)": TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;
    EventCreated: TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;

    "ResultRevealed(uint256,uint64,string)": TypedContractEvent<
      ResultRevealedEvent.InputTuple,
      ResultRevealedEvent.OutputTuple,
      ResultRevealedEvent.OutputObject
    >;
    ResultRevealed: TypedContractEvent<
      ResultRevealedEvent.InputTuple,
      ResultRevealedEvent.OutputTuple,
      ResultRevealedEvent.OutputObject
    >;

    "ResultSubmitted(uint256,address,bytes32,uint8,uint256,uint64)": TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;
    ResultSubmitted: TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;

    "ResultVerified(uint256,address,bool,string)": TypedContractEvent<
      ResultVerifiedEvent.InputTuple,
      ResultVerifiedEvent.OutputTuple,
      ResultVerifiedEvent.OutputObject
    >;
    ResultVerified: TypedContractEvent<
      ResultVerifiedEvent.InputTuple,
      ResultVerifiedEvent.OutputTuple,
      ResultVerifiedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
